package Output;


import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import models.Customer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johan
 */
public class frmCustomer extends javax.swing.JFrame {
    Customer customer = new Customer();
    frmInputCustomer inputcustomer = new frmInputCustomer();
    public frmCustomer() {
        initComponents();
        if(tampilkanDataAll()){
            tampilkanDataAll();
        }
    }
    
    public boolean tampilkanDataAll(){
     Vector<String> tableHeader = new Vector<String>();
        tableHeader.add("Id Customer");
        tableHeader.add("Nama");
        tableHeader.add("Alamat");
        tableHeader.add("Kota");
        tableHeader.add("Telp");
        tableHeader.add("Provinsi ");
        Vector tableData = customer.Load();
        if(tableData!=null){
            tabelcustomer.setModel(new DefaultTableModel(tableData,tableHeader));
            DefaultTableCellRenderer renderer=new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.RIGHT);
            tabelcustomer.getColumnModel().getColumn(2).setMinWidth(200);
            return true;
        } else return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelcustomer = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        input = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbcari = new javax.swing.JComboBox<>();
        dtcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelcustomer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, 900, 456));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Daftar Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 11, -1, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 605, -1, -1));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 605, -1, -1));

        input.setText("Input");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 605, -1, -1));

        jLabel6.setText("Cari Berdasarkan :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 20));

        cmbcari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IdCustomer", "Nama", "Alamat", "Kota", "Telp", "Provinsi" }));
        getContentPane().add(cmbcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 108, -1));
        getContentPane().add(dtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 120, -1));

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 97, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tampilkanDataAll();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        Vector<String> tableHeader = new Vector<String>();
        tableHeader.add("Id Customer");
        tableHeader.add("Nama");
        tableHeader.add("Alamat");
        tableHeader.add("Kota");
        tableHeader.add("Telp");
        tableHeader.add("Provinsi ");
        Vector tableData = customer.LookUp(cmbcari.getItemAt(cmbcari.getSelectedIndex()),dtcari.getText() );
        if(tableData!=null){
            tabelcustomer.setModel(new DefaultTableModel(tableData,tableHeader));
            DefaultTableCellRenderer renderer=new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.RIGHT);
            tabelcustomer.getColumnModel().getColumn(2).setMinWidth(200);
        } 
        
    }//GEN-LAST:event_cariActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        inputcustomer.setVisible(true);
        inputcustomer.tipe("Input");
    }//GEN-LAST:event_inputActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        if(tabelcustomer.isRowSelected(tabelcustomer.getSelectedRow())){
            inputcustomer.setVisible(true);
            inputcustomer.tipe(tabelcustomer.getValueAt(tabelcustomer.getSelectedRow(), 0).toString());
        } else JOptionPane.showMessageDialog(this, "Belum Pilih Customer");
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Hapus Data "+tabelcustomer.getValueAt(tabelcustomer.getSelectedRow(), 1).toString())==0&&customer.delete(Integer.parseInt(tabelcustomer.getValueAt(tabelcustomer.getSelectedRow(), 0).toString()))){
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            tampilkanDataAll();
        }else JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JComboBox<String> cmbcari;
    private javax.swing.JTextField dtcari;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JButton input;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelcustomer;
    // End of variables declaration//GEN-END:variables
}
