package Output;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import models.DetailRetur;
import models.Faktur;
import models.Koneksi;
import models.Penjualan;
import models.Retur;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johan
 */
public class frmDetailRetur extends javax.swing.JFrame {
    Retur faktur = new Retur();
    DetailRetur penjualan = new DetailRetur();
    public frmDetailRetur() {
        initComponents();
    }
    
    public boolean tampilkanDataAll(int nofaktur){
     Vector<String> tableHeader = new Vector<String>();
        tableHeader.add("Article");
        tableHeader.add("Deskripsi");
        tableHeader.add("Pcs");
        tableHeader.add("Harga");
        tableHeader.add("Jumlah");
        Vector tableData = penjualan.Load(nofaktur);
        if(tableData!=null){
            tabelpenjualan.setModel(new DefaultTableModel(tableData,tableHeader));
            DefaultTableCellRenderer renderer=new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.RIGHT);
            tabelpenjualan.getColumnModel().getColumn(2).setMinWidth(200);
            return true;
        } else return false;
        
        
    }
    
    public void tampilkandata(int nofaktur){
        faktur.select(nofaktur);
        String[] data = penjualan.Loaddata(nofaktur);
        tanggal.setText(data[1]);
        nama.setText(data[2]);
        kota.setText(data[3]);
        provinsi.setText(data[4]);
        diskon.setText("0");
        totalbayar.setText(data[5]);
        toko.setText(data[6]);
        int pcs=0;
        int total=0;
        for (int i = 0; i < tabelpenjualan.getRowCount(); i++) {
            pcs = pcs+Integer.parseInt(tabelpenjualan.getValueAt(i,2 ).toString());
            total = total+Integer.parseInt(tabelpenjualan.getValueAt(i,4 ).toString());
        }
        totalpcs.setText(Integer.toString(pcs));
        totalsub.setText(Integer.toString(total));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpenjualan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kota = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        toko = new javax.swing.JLabel();
        totalpcs = new javax.swing.JLabel();
        totalsub = new javax.swing.JLabel();
        diskon = new javax.swing.JLabel();
        totalbayar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        provinsi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelpenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelpenjualan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, 900, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Detail Retur");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 11, -1, -1));

        jLabel2.setText("Toko");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("Customer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        nama.setText("jLabel5");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, -1, -1));

        jLabel6.setText("Kota");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, -1));

        kota.setText("jLabel7");
        getContentPane().add(kota, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        jLabel8.setText("Total Pcs");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, -1, -1));

        jLabel9.setText("Total Sub");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, -1, -1));

        jLabel10.setText("Diskon");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, -1));

        jLabel11.setText("Total Bayar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, -1, -1));

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, 200, 70));

        toko.setText("jLabel12");
        getContentPane().add(toko, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        totalpcs.setText("jLabel5");
        getContentPane().add(totalpcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, -1, -1));

        totalsub.setText("jLabel5");
        getContentPane().add(totalsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, -1, -1));

        diskon.setText("jLabel5");
        getContentPane().add(diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, -1, -1));

        totalbayar.setText("jLabel5");
        getContentPane().add(totalbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, -1, -1));

        jLabel5.setText("Provinsi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        provinsi.setText("jLabel7");
        getContentPane().add(provinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        jLabel7.setText("Tanggal");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tanggal.setText("jLabel12");
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            File folder = new File("C:\\Project\\Faktur");
            System.out.println(folder.mkdirs());
            File file = new File("C:\\Project\\Faktur\\Faktur.jrxml");
            file.createNewFile();
            PrintWriter printf = new PrintWriter(file);
            printf.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        printf.println("<jasperReport xmlns=\"http://jasperreports.sourceforge.net/jasperreports\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd\" name=\"report name\" pageWidth=\"595\" pageHeight=\"842\" columnWidth=\"535\" leftMargin=\"20\" rightMargin=\"20\" topMargin=\"20\" bottomMargin=\"20\">");
	printf.println("<queryString>");
		printf.println("<![CDATA[select f.noRetur,f.namatoko, f.tanggal,c.nama as cnama,c.kota, c.provinsi, c.noTelepon as telp, b.article, b.deskripsi, p.jumlah, p.harga, p.jumlah*p.harga as jumlah_harga, f.totalbayar from Retur f, customer c, barang b, detailretur p where f.NoRetur=p.NoRetur and f.IdCustomer=c.IdCustomer and p.IdBarang=b.IdBarang and f.NoRetur='"+faktur.getNoRetur()+"']]>");
	printf.println("</queryString>");
	printf.println("<field name=\"noretur\" class=\"java.lang.Integer\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"namatoko\" class=\"java.lang.String\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"tanggal\" class=\"java.sql.Date\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"cnama\" class=\"java.lang.String\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"kota\" class=\"java.lang.String\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"provinsi\" class=\"java.lang.String\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"telp\" class=\"java.lang.String\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"article\" class=\"java.lang.String\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"deskripsi\" class=\"java.lang.String\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"jumlah\" class=\"java.lang.Integer\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"harga\" class=\"java.lang.Integer\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"jumlah_harga\" class=\"java.lang.Long\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"totalbayar\" class=\"java.lang.Integer\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<variable name=\"pcs\" class=\"java.lang.Integer\" calculation=\"Sum\">");
		printf.println("<variableExpression><![CDATA[$F{jumlah}]]></variableExpression>");
	printf.println("</variable>");
	printf.println("<variable name=\"totalsub\" class=\"java.lang.Long\" calculation=\"Sum\">");
		printf.println("<variableExpression><![CDATA[$F{jumlah_harga}]]></variableExpression>");
	printf.println("</variable>");
	printf.println("<background>");
		printf.println("<band/>");
	printf.println("</background>");
	printf.println("<title>");
		printf.println("<band height=\"131\">");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"-1\" y=\"1\" width=\"353\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\">");
					printf.println("<font size=\"15\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Retur Penjualan]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"0\" width=\"555\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"21\" width=\"555\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"3\" y=\"57\" width=\"50\" height=\"15\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Alamat :]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"109\" width=\"556\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"0\" width=\"1\" height=\"130\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"53\" width=\"556\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"394\" y=\"0\" width=\"80\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Tgl Retur]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"475\" y=\"1\" width=\"80\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[No Retur]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"392\" y=\"0\" width=\"1\" height=\"130\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"474\" y=\"0\" width=\"1\" height=\"54\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"555\" y=\"0\" width=\"1\" height=\"130\"/>");
			printf.println("</line>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"394\" y=\"54\" width=\"161\" height=\"14\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Customer]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"393\" y=\"68\" width=\"162\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"475\" y=\"21\" width=\"80\" height=\"31\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$F{noretur}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField pattern=\"dd/MM/yyyy\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"394\" y=\"22\" width=\"80\" height=\"31\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.util.Date\"><![CDATA[$F{tanggal}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"55\" y=\"58\" width=\"182\" height=\"16\"/>");
				printf.println("<textElement>");
					printf.println("<font size=\"11\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Jl. Sauyunan IX no. 15A Bandung.]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"55\" y=\"73\" width=\"138\" height=\"16\"/>");
				printf.println("<textElement/>");
				printf.println("<text><![CDATA[Telp / Fax. 022-85447612]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"55\" y=\"88\" width=\"153\" height=\"16\"/>");
				printf.println("<textElement/>");
				printf.println("<text><![CDATA[Hp / Wa. 08112311009]]></text>");
			printf.println("</staticText>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"397\" y=\"69\" width=\"159\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.String\"><![CDATA[$F{cnama}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"397\" y=\"89\" width=\"158\" height=\"20\"/>");
				printf.println("<textElement/>");
				printf.println("<textFieldExpression class=\"java.lang.String\"><![CDATA[$F{kota}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"3\" y=\"110\" width=\"90\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"97\" y=\"110\" width=\"294\" height=\"21\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[]]></text>");
			printf.println("</staticText>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"394\" y=\"110\" width=\"161\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.String\"><![CDATA[$F{provinsi}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField>");
				printf.println("<reportElement x=\"9\" y=\"22\" width=\"374\" height=\"30\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font size=\"12\" isBold=\"false\"/>");
				printf.println("</textElement>");
				printf.println("<textFieldExpression class=\"java.lang.String\"><![CDATA[$F{namatoko}]]></textFieldExpression>");
			printf.println("</textField>");
		printf.println("</band>");
	printf.println("</title>");
	printf.println("<pageHeader>");
		printf.println("<band/>");
	printf.println("</pageHeader>");
	printf.println("<columnHeader>");
		printf.println("<band height=\"21\">");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"3\" y=\"0\" width=\"90\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font isBold=\"true\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Artikel]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"97\" y=\"0\" width=\"294\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font isBold=\"true\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Deskripsi Barang]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"394\" y=\"0\" width=\"40\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font isBold=\"true\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Pcs]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"438\" y=\"0\" width=\"53\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font isBold=\"true\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Harga]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"494\" y=\"0\" width=\"61\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font isBold=\"true\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Jumlah]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"94\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"392\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"435\" y=\"-1\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"491\" y=\"-1\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"555\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"20\" width=\"556\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"-1\" width=\"557\" height=\"1\"/>");
			printf.println("</line>");
		printf.println("</band>");
	printf.println("</columnHeader>");
	printf.println("<detail>");
		printf.println("<band height=\"21\">");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"3\" y=\"0\" width=\"90\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.String\"><![CDATA[$F{article}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"20\" width=\"555\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"94\" y=\"0\" width=\"1\" height=\"20\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"392\" y=\"0\" width=\"1\" height=\"20\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"435\" y=\"0\" width=\"1\" height=\"20\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"491\" y=\"0\" width=\"1\" height=\"20\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"555\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"97\" y=\"-1\" width=\"294\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.String\"><![CDATA[$F{deskripsi}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"394\" y=\"-1\" width=\"40\" height=\"22\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$F{jumlah}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField pattern=\"#,##0\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"438\" y=\"-1\" width=\"54\" height=\"22\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$F{harga}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField pattern=\"#,##0\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"494\" y=\"0\" width=\"61\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Left\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Long\"><![CDATA[$F{jumlah_harga}]]></textFieldExpression>");
			printf.println("</textField>");
		printf.println("</band>");
	printf.println("</detail>");
	printf.println("<columnFooter>");
		printf.println("<band height=\"3\"/>");
	printf.println("</columnFooter>");
	printf.println("<pageFooter>");
		printf.println("<band height=\"5\"/>");
	printf.println("</pageFooter>");
	printf.println("<summary>");
		printf.println("<band height=\"145\">");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"80\" width=\"556\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"555\" y=\"0\" width=\"1\" height=\"80\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"0\" width=\"1\" height=\"81\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"392\" y=\"0\" width=\"1\" height=\"80\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"20\" width=\"556\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"289\" y=\"-1\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Right\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Total Pcs]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"289\" y=\"19\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Right\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Total Sub]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"289\" y=\"39\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Right\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Diskon]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"289\" y=\"59\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Right\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Total Bayar]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"40\" width=\"557\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"59\" width=\"555\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"396\" y=\"0\" width=\"159\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Left\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$V{pcs}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField pattern=\"#,##0\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"396\" y=\"21\" width=\"159\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Long\"><![CDATA[$V{totalsub}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"396\" y=\"40\" width=\"159\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[0]]></text>");
			printf.println("</staticText>");
			printf.println("<textField pattern=\"#,##0\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"396\" y=\"60\" width=\"159\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$F{totalbayar}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"16\" y=\"81\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\">");
					printf.println("<font size=\"8\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Mengetahui]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"16\" y=\"101\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\">");
					printf.println("<font size=\"8\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Gudang]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"137\" y=\"81\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\">");
					printf.println("<font size=\"8\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Checker]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"252\" y=\"81\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\">");
					printf.println("<font size=\"8\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Disetujui]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"46\" y=\"137\" width=\"42\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"167\" y=\"136\" width=\"42\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"282\" y=\"135\" width=\"42\" height=\"1\"/>");
			printf.println("</line>");
		printf.println("</band>");
	printf.println("</summary>");
printf.println("</jasperReport>");

printf.close();
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            Logger.getLogger(frmDetailRetur.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Koneksi con = new Koneksi();        
        String is = "C:\\Project\\Faktur\\Faktur.jrxml" ;
        Map map = new HashMap(); 
        map.put("judul", "Laporan / Daftar …");
        con.bukaKoneksi();        
        try{
           JasperReport jasperReport = JasperCompileManager.compileReport(is);
           JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,map,con.dbKoneksi);
           JasperViewer.viewReport(jasperPrint,false);

        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDetailFaktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDetailFaktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDetailFaktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDetailFaktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDetailFaktur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diskon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kota;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel provinsi;
    private javax.swing.JTable tabelpenjualan;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel toko;
    private javax.swing.JLabel totalbayar;
    private javax.swing.JLabel totalpcs;
    private javax.swing.JLabel totalsub;
    // End of variables declaration//GEN-END:variables
}
