package Output;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import models.Barang;
import models.Customer;
import models.Faktur;
import models.FakturPembelian;
import models.Koneksi;
import models.Pabrik;
import models.Pembelian;
import models.Penjualan;
import models.Sales;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johan
 */
public class frmPembelian extends javax.swing.JFrame {
    Pembelian pembelian = new Pembelian();
    Barang barang = new Barang();
    Pabrik pabrik = new Pabrik();
    FakturPembelian faktur = new FakturPembelian();
    Vector vtabelpenjualan =new Vector();
    
    public frmPembelian() {
        initComponents();
        setExtendedState(frmPembelian.MAXIMIZED_BOTH);
        if(tampilkanDataAll()){
            tampilkanDataAll();
        }
        if(!pabrik.Load().isEmpty()){
            tampilkanCustomer();
        }
        ((DefaultTableModel)tabelpenjualan.getModel()).setNumRows(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        Masukan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbbarang = new javax.swing.JComboBox<>();
        hariini = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelpenjualan = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalpcs = new javax.swing.JTextField();
        totalsub = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        totalbayar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        tanggal = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelcustomer = new javax.swing.JTable();
        tcustomer = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbcustomer = new javax.swing.JComboBox<>();
        caricustomer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        caribarang = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tanggal :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 20));

        jLabel4.setText("Pabrik :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 80, 20));

        jLabel5.setText("Pabrik Terpilih :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 130, 20));

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelbarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabelbarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 910, 130));

        Masukan.setText("Masukan");
        Masukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukanActionPerformed(evt);
            }
        });
        getContentPane().add(Masukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, -1, -1));

        jLabel6.setText("Cari Berdasarkan :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 20));

        cmbbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "idBarang", "Article", "Deskripsi" }));
        getContentPane().add(cmbbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 110, -1));

        hariini.setText("Hari Ini");
        hariini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hariiniActionPerformed(evt);
            }
        });
        getContentPane().add(hariini, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        tabelpenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpenjualan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabelpenjualanPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tabelpenjualan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 910, 180));

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 80, -1));

        jLabel2.setText("Total Pcs :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 60, 20));

        jLabel7.setText("Total Sub :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 60, 20));

        jLabel8.setText("Diskon :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 50, 20));

        jLabel9.setText("Total Bayar : ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 70, 20));

        totalpcs.setEditable(false);
        getContentPane().add(totalpcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 110, -1));

        totalsub.setEditable(false);
        getContentPane().add(totalsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 110, -1));

        diskon.setText("0");
        getContentPane().add(diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 110, -1));
        getContentPane().add(totalbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 110, -1));

        jButton4.setText("Hitung");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, -1, -1));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 130, -1));

        tabelcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelcustomer);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, 90));
        getContentPane().add(tcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 140, 20));

        jLabel11.setText("Cari Pabrik Berdasarkan :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 20));

        cmbcustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "Alamat", "Tlp", "Provinsi" }));
        getContentPane().add(cmbcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 110, 20));
        getContentPane().add(caricustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 150, -1));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));
        getContentPane().add(caribarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 120, -1));

        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jButton5.setText("Pilih");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, -1));

        jButton6.setText("Simpan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 200, 80));

        jButton7.setText("test");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hariiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hariiniActionPerformed
        DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        tanggal.setText(format.format(Calendar.getInstance().getTime()));
    }//GEN-LAST:event_hariiniActionPerformed

    private void MasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukanActionPerformed
        boolean bisa= true;
        for (int i = 0; i < tabelpenjualan.getRowCount(); i++) {
            if(Integer.parseInt(tabelpenjualan.getValueAt(i, 0).toString())==Integer.parseInt(tabelbarang.getValueAt(tabelbarang.getSelectedRow(), 0).toString())){
                bisa = false;
                i = tabelpenjualan.getRowCount();
            } else bisa = true;
        }
        if(tcustomer.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Belum Memilih Customer");
        }else if(!bisa){
            JOptionPane.showMessageDialog(this, "Barang Sudah Ada");
        }else if(tabelbarang.isRowSelected(tabelbarang.getSelectedRow())){
            
        Vector<Object> row= new Vector<Object>();
        row.add(tabelbarang.getValueAt(tabelbarang.getSelectedRow(), 0));
        row.add(tabelbarang.getValueAt(tabelbarang.getSelectedRow(), 1));
        row.add(tabelbarang.getValueAt(tabelbarang.getSelectedRow(), 2));
        String input = JOptionPane.showInputDialog("Masukan Jumlah :");
        int jumlah=0;
        
        if(input!=null){
            try{
            jumlah = Integer.parseInt(input);
            } catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Masukan Jumlah Dengan Benar");
            }
        }
        row.add(jumlah);
        String harga = JOptionPane.showInputDialog(this, "Masukan Harga Barang :");
        int hargaa=0;
        if(harga!=null){
            try{
            hargaa = Integer.parseInt(harga);
            } catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Masukan Harga dengan Benar");
            }
        }
        row.add(hargaa);
        row.add(jumlah*hargaa);
        vtabelpenjualan.add(row);   
        Vector<String> tableHeader = new Vector<String>();
        tableHeader.add("Id Barang");
        tableHeader.add("Article");
        tableHeader.add("Deskripsi Barang");
        tableHeader.add("Pcs");
        tableHeader.add("Harga");
        tableHeader.add("Jumlah");
        Vector tableData = vtabelpenjualan;
        if(tableData!=null){
            tabelpenjualan.setModel(new DefaultTableModel(tableData,tableHeader));
            DefaultTableCellRenderer renderer=new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.RIGHT);
            tabelpenjualan.getColumnModel().getColumn(2).setMinWidth(200);
        } 
        }
        
    }//GEN-LAST:event_MasukanActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    if(tabelcustomer.isRowSelected(tabelcustomer.getSelectedRow())){
        if(tabelpenjualan.getRowCount()!=0){
                ((DefaultTableModel)tabelpenjualan.getModel()).setNumRows(0);
        }
    pabrik.select(Integer.parseInt(tabelcustomer.getValueAt(tabelcustomer.getSelectedRow(), 0).toString()));
    tcustomer.setText(pabrik.getNamaPabrik());
    } else JOptionPane.showMessageDialog(this, "Belum Memilih Customer");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tabelpenjualanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabelpenjualanPropertyChange
        int ttotalpcs=0;
        int ttotalsub=0;
        if(tabelpenjualan.getValueAt(0, 0)!=null){
            for (int i = 0; i < tabelpenjualan.getRowCount(); i++) {
                ttotalpcs += Integer.parseInt(tabelpenjualan.getValueAt(i, 3).toString());
                ttotalsub += Integer.parseInt(tabelpenjualan.getValueAt(i, 5).toString());
            }
        }
        totalpcs.setText(Integer.toString(ttotalpcs));
        totalsub.setText(Integer.toString(ttotalsub));
    }//GEN-LAST:event_tabelpenjualanPropertyChange

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        totalbayar.setText(Integer.toString(Integer.parseInt(totalsub.getText())-Integer.parseInt(diskon.getText())));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            Integer.parseInt(diskon.getText());
            Integer.parseInt(totalbayar.getText());

        if(tanggal.getText().toCharArray().length==0){
            JOptionPane.showMessageDialog(this, "Tolong Masukan Tanggal");
        } else if(tcustomer.getText().toCharArray().length==0){
            JOptionPane.showMessageDialog(this, "Customer Tidak Boleh Kosong");
        }else if(tabelpenjualan.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Belum ada Barang yang masuk");
        }else if(totalbayar.getText().toCharArray().length==0){
            JOptionPane.showMessageDialog(this, "Total Bayar Tidak Boleh Kosong");
        } else{
            if(JOptionPane.showConfirmDialog(this, "Simpan Data?\n"
                + "Faktur akan dicetak dan stok barang akan bertambah")!=0){
            
        }else{
        int nofaktur = faktur.nofakturbaru();
        for (int i = 0; i < tabelpenjualan.getRowCount(); i++) {
            pembelian.setIdPenjualan(pembelian.idpenjualanbaru());
            pembelian.setNoFaktur(nofaktur);
            pembelian.setIdBarang(Integer.parseInt(tabelpenjualan.getValueAt(i,0).toString()));
            pembelian.setHarga(Integer.parseInt(tabelpenjualan.getValueAt(i, 4).toString()));
            pembelian.setJumlah(Integer.parseInt(tabelpenjualan.getValueAt(i, 3).toString()));
            barang.kurangstok(Integer.parseInt(tabelpenjualan.getValueAt(i,0).toString()), Integer.parseInt(tabelpenjualan.getValueAt(i, 3).toString()));
            pembelian.insert();
        }
        faktur.setNoFaktur(nofaktur);
        faktur.setIdPabrik(pabrik.getIdPabrik());
        String[] date=tanggal.getText().split("-");
        faktur.setTanggal(Date.valueOf(date[2]+"-"+date[1]+"-"+date[0]));
        faktur.setDiskon(Integer.parseInt(diskon.getText()));
        faktur.setTotalBayar(Integer.parseInt(totalbayar.getText()));
        faktur.setStatus("Belum Selesai");
        faktur.insert();
        
        try {
            File folder = new File("C:\\Project\\Faktur");
            File file = new File("C:\\Project\\Faktur\\Faktur.jrxml");
            file.createNewFile();
            PrintWriter printf = new PrintWriter(file);
            printf.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        printf.println("<jasperReport xmlns=\"http://jasperreports.sourceforge.net/jasperreports\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd\" name=\"report name\" pageWidth=\"595\" pageHeight=\"842\" columnWidth=\"535\" leftMargin=\"20\" rightMargin=\"20\" topMargin=\"20\" bottomMargin=\"20\">");
	printf.println("<queryString>");
		printf.println("<![CDATA[select f.nofaktur, f.tanggal,c.namapabrik as cnama, c.telp, b.article, b.deskripsi, p.jumlah, p.harga, p.jumlah*p.harga as jumlah_harga, f.diskon, f.total from fakturbeli f, pabrik c, barang b, pembelian p where f.NoFaktur=p.NoFaktur and f.IdPabrik=c.IdPabrik and p.IdBarang=b.IdBarang and f.NoFaktur='"+nofaktur+"']]>");
	printf.println("</queryString>");
	printf.println("<field name=\"nofaktur\" class=\"java.lang.Integer\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"tanggal\" class=\"java.sql.Date\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"cnama\" class=\"java.lang.String\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"article\" class=\"java.lang.String\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"deskripsi\" class=\"java.lang.String\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"jumlah\" class=\"java.lang.Integer\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"harga\" class=\"java.lang.Integer\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"jumlah_harga\" class=\"java.lang.Long\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"diskon\" class=\"java.lang.Integer\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<field name=\"total\" class=\"java.lang.Integer\">");
		printf.println("<fieldDescription><![CDATA[]]></fieldDescription>");
	printf.println("</field>");
	printf.println("<variable name=\"pcs\" class=\"java.lang.Integer\" calculation=\"Sum\">");
		printf.println("<variableExpression><![CDATA[$F{jumlah}]]></variableExpression>");
	printf.println("</variable>");
	printf.println("<variable name=\"totalsub\" class=\"java.lang.Long\" calculation=\"Sum\">");
		printf.println("<variableExpression><![CDATA[$F{jumlah_harga}]]></variableExpression>");
	printf.println("</variable>");
	printf.println("<background>");
		printf.println("<band/>");
	printf.println("</background>");
	printf.println("<title>");
		printf.println("<band height=\"131\">");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"-1\" y=\"1\" width=\"353\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\">");
					printf.println("<font size=\"15\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Faktur Pembelian]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"0\" width=\"555\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"21\" width=\"555\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"3\" y=\"57\" width=\"50\" height=\"15\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Alamat :]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"109\" width=\"556\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"0\" width=\"1\" height=\"130\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"53\" width=\"556\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"394\" y=\"0\" width=\"80\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Tgl Faktur]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"475\" y=\"1\" width=\"80\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[No Faktur]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"392\" y=\"0\" width=\"1\" height=\"130\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"474\" y=\"0\" width=\"1\" height=\"54\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"555\" y=\"0\" width=\"1\" height=\"130\"/>");
			printf.println("</line>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"394\" y=\"54\" width=\"161\" height=\"14\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Pabrik]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"393\" y=\"68\" width=\"162\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"475\" y=\"21\" width=\"80\" height=\"31\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$F{nofaktur}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField pattern=\"dd/MM/yyyy\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"394\" y=\"22\" width=\"80\" height=\"31\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.util.Date\"><![CDATA[$F{tanggal}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"55\" y=\"58\" width=\"182\" height=\"16\"/>");
				printf.println("<textElement>");
					printf.println("<font size=\"11\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Jl. Sauyunan IX no. 15A Bandung.]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"55\" y=\"73\" width=\"138\" height=\"16\"/>");
				printf.println("<textElement/>");
				printf.println("<text><![CDATA[Telp / Fax. 022-85447612]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"55\" y=\"88\" width=\"153\" height=\"16\"/>");
				printf.println("<textElement/>");
				printf.println("<text><![CDATA[Hp / Wa. 08112311009]]></text>");
			printf.println("</staticText>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"397\" y=\"69\" width=\"159\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.String\"><![CDATA[$F{cnama}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"3\" y=\"110\" width=\"90\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[]]></text>");
			printf.println("</staticText>");
		printf.println("</band>");
	printf.println("</title>");
	printf.println("<pageHeader>");
		printf.println("<band/>");
	printf.println("</pageHeader>");
	printf.println("<columnHeader>");
		printf.println("<band height=\"21\">");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"3\" y=\"0\" width=\"90\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font isBold=\"true\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Artikel]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"97\" y=\"0\" width=\"294\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font isBold=\"true\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Deskripsi Barang]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"394\" y=\"0\" width=\"40\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font isBold=\"true\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Pcs]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"438\" y=\"0\" width=\"53\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font isBold=\"true\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Harga]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"494\" y=\"0\" width=\"61\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\">");
					printf.println("<font isBold=\"true\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Jumlah]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"94\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"392\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"435\" y=\"-1\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"491\" y=\"-1\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"555\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"20\" width=\"556\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"-1\" width=\"557\" height=\"1\"/>");
			printf.println("</line>");
		printf.println("</band>");
	printf.println("</columnHeader>");
	printf.println("<detail>");
		printf.println("<band height=\"21\">");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"3\" y=\"0\" width=\"90\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.String\"><![CDATA[$F{article}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"20\" width=\"555\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"94\" y=\"0\" width=\"1\" height=\"20\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"392\" y=\"0\" width=\"1\" height=\"20\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"435\" y=\"0\" width=\"1\" height=\"20\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"491\" y=\"0\" width=\"1\" height=\"20\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"555\" y=\"0\" width=\"1\" height=\"21\"/>");
			printf.println("</line>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"97\" y=\"-1\" width=\"294\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.String\"><![CDATA[$F{deskripsi}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"394\" y=\"-1\" width=\"40\" height=\"22\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$F{jumlah}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField pattern=\"#,##0\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"438\" y=\"-1\" width=\"54\" height=\"22\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$F{harga}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField pattern=\"#,##0\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"494\" y=\"0\" width=\"61\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Left\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Long\"><![CDATA[$F{jumlah_harga}]]></textFieldExpression>");
			printf.println("</textField>");
		printf.println("</band>");
	printf.println("</detail>");
	printf.println("<columnFooter>");
		printf.println("<band height=\"3\"/>");
	printf.println("</columnFooter>");
	printf.println("<pageFooter>");
		printf.println("<band height=\"5\"/>");
	printf.println("</pageFooter>");
	printf.println("<summary>");
		printf.println("<band height=\"145\">");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"80\" width=\"556\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"555\" y=\"0\" width=\"1\" height=\"80\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"0\" width=\"1\" height=\"81\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"392\" y=\"0\" width=\"1\" height=\"80\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"20\" width=\"556\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"289\" y=\"-1\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Right\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Total Pcs]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"289\" y=\"19\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Right\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Total Sub]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"289\" y=\"39\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Right\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Diskon]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"289\" y=\"59\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Right\" verticalAlignment=\"Middle\"/>");
				printf.println("<text><![CDATA[Total Bayar]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"-1\" y=\"40\" width=\"557\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"0\" y=\"59\" width=\"555\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<textField hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"396\" y=\"0\" width=\"159\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Left\" verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$V{pcs}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField pattern=\"#,##0\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"396\" y=\"21\" width=\"159\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Long\"><![CDATA[$V{totalsub}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField pattern=\"#,##0\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"396\" y=\"40\" width=\"159\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$F{diskon}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<textField pattern=\"#,##0\" hyperlinkType=\"None\">");
				printf.println("<reportElement x=\"396\" y=\"60\" width=\"159\" height=\"20\"/>");
				printf.println("<textElement verticalAlignment=\"Middle\"/>");
				printf.println("<textFieldExpression class=\"java.lang.Integer\"><![CDATA[$F{total}]]></textFieldExpression>");
			printf.println("</textField>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"16\" y=\"81\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\">");
					printf.println("<font size=\"8\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Mengetahui]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"16\" y=\"101\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\">");
					printf.println("<font size=\"8\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Gudang]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"137\" y=\"81\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\">");
					printf.println("<font size=\"8\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Checker]]></text>");
			printf.println("</staticText>");
			printf.println("<staticText>");
				printf.println("<reportElement x=\"252\" y=\"81\" width=\"100\" height=\"20\"/>");
				printf.println("<textElement textAlignment=\"Center\" verticalAlignment=\"Middle\">");
					printf.println("<font size=\"8\"/>");
				printf.println("</textElement>");
				printf.println("<text><![CDATA[Disetujui]]></text>");
			printf.println("</staticText>");
			printf.println("<line>");
				printf.println("<reportElement x=\"46\" y=\"137\" width=\"42\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"167\" y=\"136\" width=\"42\" height=\"1\"/>");
			printf.println("</line>");
			printf.println("<line>");
				printf.println("<reportElement x=\"282\" y=\"135\" width=\"42\" height=\"1\"/>");
			printf.println("</line>");
		printf.println("</band>");
	printf.println("</summary>");
printf.println("</jasperReport>");

printf.close();
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        }
        
        Koneksi con = new Koneksi();        
        String is = "C:\\Project\\Faktur\\Faktur.jrxml" ;
        Map map = new HashMap(); 
        map.put("judul", "Laporan / Daftar …");
        con.bukaKoneksi();        
        try{
           JasperReport jasperReport = JasperCompileManager.compileReport(is);
           JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,map,con.dbKoneksi);
           JasperViewer.viewReport(jasperPrint,false);

        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        }
        }
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this, "Masukan Angka");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(tabelpenjualan.getSelectedRow()>=0){
            if(JOptionPane.showConfirmDialog(this, "Hapus ?")==0){
            DefaultTableModel dm = (DefaultTableModel)tabelpenjualan.getModel();
        dm.removeRow(tabelpenjualan.getSelectedRow());
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Vector<String> tableHeader = new Vector<String>();
        tableHeader.add("Id Customer");
        tableHeader.add("Nama");
        tableHeader.add("Alamat");
        tableHeader.add("Kota");
        tableHeader.add("Provinsi");
        Vector tableData = pabrik.LookUp(cmbcustomer.getItemAt(cmbcustomer.getSelectedIndex()), caricustomer.getText());
        if(tableData!=null){
            tabelcustomer.setModel(new DefaultTableModel(tableData,tableHeader));
            DefaultTableCellRenderer renderer=new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.RIGHT);
            tabelcustomer.getColumnModel().getColumn(0).setMinWidth(20);
            tabelcustomer.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabelcustomer.getColumnModel().getColumn(2).setMinWidth(150);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Vector<String> tableHeader = new Vector<String>();
        tableHeader.add("Id Barang");
        tableHeader.add("Article");
        tableHeader.add("Deskripsi");
        tableHeader.add("Harga Jawa Barat");
        tableHeader.add("Harga Jawa Timur");
        tableHeader.add("Harga Jawa Tengah");
        tableHeader.add("Stok ");
        Vector tableData = barang.LookUp(cmbbarang.getItemAt(cmbbarang.getSelectedIndex()), caribarang.getText());
        if(tableData!=null){
            tabelbarang.setModel(new DefaultTableModel(tableData,tableHeader));
            DefaultTableCellRenderer renderer=new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.RIGHT);
            tabelbarang.getColumnModel().getColumn(2).setMinWidth(200);
            tabelbarang.getColumnModel().getColumn(6).setMinWidth(30);
            tabelbarang.getColumnModel().getColumn(6).setPreferredWidth(30);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPembelian().setVisible(true);
            }
        });
    }

    public boolean tampilkanDataAll(){
     Vector<String> tableHeader = new Vector<String>();
        tableHeader.add("Id Barang");
        tableHeader.add("Article");
        tableHeader.add("Deskripsi");
        tableHeader.add("Harga Jawa Barat");
        tableHeader.add("Harga Jawa Timur");
        tableHeader.add("Harga Jawa Tengah");
        tableHeader.add("Stok ");
        Vector tableData = barang.Load();
        if(tableData!=null){
            tabelbarang.setModel(new DefaultTableModel(tableData,tableHeader));
            DefaultTableCellRenderer renderer=new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.RIGHT);
            tabelbarang.getColumnModel().getColumn(2).setMinWidth(200);
            tabelbarang.getColumnModel().getColumn(6).setMinWidth(30);
            tabelbarang.getColumnModel().getColumn(6).setPreferredWidth(30);
            return true;
        } else return false;
    }
    
    public boolean tampilkanCustomer(){
     Vector<String> tableHeader = new Vector<String>();
        tableHeader.add("Id Pabrik");
        tableHeader.add("Nama");
        tableHeader.add("Alamat");
        tableHeader.add("Telp");
        Vector tableData = pabrik.Load();
        if(tableData!=null){
            tabelcustomer.setModel(new DefaultTableModel(tableData,tableHeader));
            DefaultTableCellRenderer renderer=new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.RIGHT);
            tabelcustomer.getColumnModel().getColumn(0).setMinWidth(20);
            tabelcustomer.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabelcustomer.getColumnModel().getColumn(2).setMinWidth(150);
            return true;
        } else return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Masukan;
    private javax.swing.JTextField caribarang;
    private javax.swing.JTextField caricustomer;
    private javax.swing.JComboBox<String> cmbbarang;
    private javax.swing.JComboBox<String> cmbcustomer;
    private javax.swing.JTextField diskon;
    private javax.swing.JButton hariini;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTable tabelcustomer;
    private javax.swing.JTable tabelpenjualan;
    private javax.swing.JTextField tanggal;
    private javax.swing.JLabel tcustomer;
    private javax.swing.JTextField totalbayar;
    private javax.swing.JTextField totalpcs;
    private javax.swing.JTextField totalsub;
    // End of variables declaration//GEN-END:variables
}